### ISSUE TITLE
I get this issue when running `node .`

### ISSUE THREAD

**Issue by pani7777** [outlaylol/mee6-but-better#15]
internal/modules/cjs/loader.js:969
  throw err;
  ^

```
Error: Cannot find module 'C:\Users\pani'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by axluu** [comment]
very cool

**Comment by SeanLovesMCDEV** [comment]
I can code and you need to create an app in the discord dev portal the do all the other stuff

**Comment by satyam-l** [comment]
Interesting

**Comment by Spongeyboi** [comment]
You must run `node faith.js` as no index.js exists. This is changeable in package.json
