### ISSUE TITLE
Again a error encountered 

### ISSUE THREAD

**Issue by Priyanshu348** [outlaylol/mee6-but-better#6]
(node:888) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/rbd/pnpm-volume/9a08be70-a51a-494a-8577-ed7fc88a80bb/node_modules/.registry.npmjs.org/discord.js/12.1.1/node_modules/discord.js/src/structures/MessageEmbed.js:436:8)
    at MessageEmbed.addFields (/rbd/pnpm-volume/9a08be70-a51a-494a-8577-ed7fc88a80bb/node_modules/.registry.npmjs.org/discord.js/12.1.1/node_modules/discord.js/src/structures/MessageEmbed.js:252:42)
    at MessageEmbed.addField (/rbd/pnpm-volume/9a08be70-a51a-494a-8577-ed7fc88a80bb/node_modules/.registry.npmjs.org/discord.js/12.1.1/node_modules/discord.js/src/structures/MessageEmbed.js:243:17)
at Object.exports.run (/app/commands/help.js:8:6)
at Client.client.on (/app/faith.js:213:9)
    at Client.emit (events.js:189:13)

**Comment by outlaylol** [comment]
Update node
